# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [6]:

import numpy as np

m1= np.array([1,2,3,4,5,6,7,8,9])
m3=m1.reshape(3,3)

m2= np.array([1,2,3,4,5,6,7,8,9])
m4=m1.reshape(3,3)

m5=m3+m4

print(m5)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### 2. Write a Python Program to Multiply Two Matrices?

In [7]:
m1= np.array([1,2,3,4,5,6,7,8,9])
m3=m1.reshape(3,3)

m2= np.array([1,2,3,4,5,6,7,8,9])
m4=m1.reshape(3,3)

m5=m3*m4

print(m5)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 3. Write a Python Program to Transpose a Matrix?

In [18]:
m1= np.array([1,2,3,4,5,6,7,8,])
m3=m1.reshape(4,2)



m5=m3.transpose()
print("Initional matrix:"'\n',m3)
print("transposed matrix:"'\n',m5)

Initional matrix:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
transposed matrix:
 [[1 3 5 7]
 [2 4 6 8]]



### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [19]:
my_list = ((input("enter the words separated by semicolon(;):")))
#print(words)
my_list =my_list .split(',')
#my_list = ['Yash', 'Divya', 'Milan']
my_list.sort()
print(my_list)

enter the words separated by semicolon(;): yash,divya,milan


['divya', 'milan', 'yash']


### 5. Write a Python Program to Remove Punctuation From a String?

In [21]:
import string

def remove_punctuation(input_string):

    translator = str.maketrans('', '', string.punctuation)
   
    no_punct = input_string.translate(translator)
    return no_punct

my_string = "Hello! How are you doing?"
print(remove_punctuation(my_string))

Hello How are you doing


In [ ]:
ujcj
